<a href="https://colab.research.google.com/github/verma-satyam/ML-Codiing-Ninjas/blob/main/3.%20MultiVariable%20Regression%20and%20Gradient%20Descent/1_Find_More_Complex_Boundaries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
from sklearn import datasets

In [31]:
boston = datasets.load_boston()

X = boston.data
Y = boston.target

In [32]:
import pandas as pd
df = pd.DataFrame(X)
print(boston.feature_names)
df.columns = boston.feature_names
for i  in range(boston.feature_names.size-1):
  for j in range(boston.feature_names.size-1):
    s = boston.feature_names[i] + "_" + boston.feature_names[j]
    df[s] = df[boston.feature_names[i]] * df[boston.feature_names[j]]
df.describe()

['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']

             CRIM          ZN  ...    B_PTRATIO            B_B
count  506.000000  506.000000  ...   506.000000     506.000000
mean     3.613524   11.363636  ...  6547.619334  135534.645253
std      8.601545   23.322453  ...  1837.557901   41830.850997
min      0.006320    0.000000  ...     6.464000       0.102400
25%      0.082045    0.000000  ...  6140.250000  140908.274275
50%      0.256510    0.000000  ...  7078.025500  153225.273700
75%      3.677083   12.500000  ...  7695.286500  156994.250700
max     88.976200  100.000000  ...  8421.600000  157529.610000

[8 rows x 157 columns]

In [33]:
df.shape[1]

157

In [24]:
from sklearn import model_selection
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X,Y,random_state = 0)
X2_train, X2_test, Y2_train, Y2_test = model_selection.train_test_split(df,Y,random_state = 0)

In [25]:
from sklearn.linear_model import LinearRegression
alg1 = LinearRegression()
alg2 = LinearRegression()

In [26]:
alg1.fit(X_train, Y_train)
alg2.fit(X2_train, Y2_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [27]:
Y_pred = alg1.predict(X_test)
train_score = alg1.score(X_train, Y_train)
test_score = alg1.score(X_test, Y_test)
print("Train Score: ", train_score)
print("Test Score: ", test_score)

Train Score:  0.7697699488741149
Test Score:  0.635463843320211

In [28]:
Y2_pred = alg2.predict(X2_test)
train2_score = alg2.score(X2_train, Y2_train)
test2_score = alg2.score(X2_test, Y2_test)
print("Train2 Score: ", train2_score)
print("Test2 Score: ", test2_score)

Train2 Score:  0.9253702734515877
Test2 Score:  0.640557469776029